# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d6624eacdc00a096aa5c97a514a51464126d0d53635376bc34f5f6bc638b231c68594067511c48ed52b2739b19ce91c82f8075c4cdef8ece9bb6047124ab296

test:
  secret_key_base: 4ea98e09dd9c4d0f63d36f2bc620132f39457f8b8b4840a5e4ec607a9da5b17609e8012eb9536983be064bc0150cc47688aba24fc109183512cf3d4671d3f0c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
